### ISSUE TITLE
.jade files in /app/jade/ not rendering as html in /.tmp

### ISSUE THREAD

**Issue by bumpux** [yfr/generator-jade#31]
I've got the generator working and serving locally -- my changes to index.jade and main.styl render as expected in `/.tmp` and preview fine in the browser. But when I create new .jade files in `/app/jade/` they don't get created as new .html in `/.tmp`. Also, nothing happens when I create subfolders under `/app/jade/` as described in the readme.

Could I have missed something in setting up or config?

**Comment by d2tstudio** [comment]
+1

**Comment by d2tstudio** [comment]
@bumpux I fixed it by updating the missing pages to the jade task. I thought the generator would do this automatically, but we need to add it for every page.

src: ['index.jade','post/index.jade'],

**Comment by Poltergeist** [comment]
Made a PR for this so jade files get generated recursive. Files starting with an underscore are omitted.

**Comment by yfr** [comment]
Please use globbing in grunt config: http://gruntjs.com/configuring-tasks#globbing-patterns
